from pandas import DataFrame
from typing import Any

def stock_zh_a_spot_em(*args: Any, **kwargs: Any) -> DataFrame: ...
def stock_zh_a_spot(*args: Any, **kwargs: Any) -> DataFrame: ...
def stock_zh_a_hist(*args: Any, **kwargs: Any) -> DataFrame: ...
def stock_zh_a_daily(*args: Any, **kwargs: Any) -> DataFrame: ...
